# Generated by Django 2.1.3 on 2018-11-14 10:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoPublicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('creado', models.DateTimeField(default=datetime.datetime(2018, 11, 14, 10, 27, 28, 389413, tzinfo=utc))),
                ('editado', models.DateTimeField(default=datetime.datetime(2018, 11, 14, 10, 27, 28, 389443, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoP', models.CharField(max_length=50)),
                ('apellidoM', models.CharField(max_length=50)),
                ('codigoVerificacion', models.CharField(max_length=6)),
                ('verificado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(default=datetime.datetime(2018, 11, 14, 10, 27, 28, 388810, tzinfo=utc))),
                ('editado', models.DateTimeField(default=datetime.datetime(2018, 11, 14, 10, 27, 28, 388839, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
        migrations.AddField(
            model_name='archivopublicacion',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Publicacion'),
        ),
    ]
