# Generated by Django 2.1.3 on 2018-11-15 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20181114_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 11, 13, 6, 473451, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='editado',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 11, 13, 6, 473482, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 11, 13, 6, 472692, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='editado',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 11, 13, 6, 472725, tzinfo=utc)),
        ),
    ]
